#!/usr/bin/bash

Dim="\e[0;2m"
Bold="\e[0;1m"
BRed="\e[0;1;31m"
BBlue="\e[0;1;34m"
BGreen="\e[0;1;32m"
Clear="\e[0m"

err() { echo -e "$Dim[${BRed}Error$Dim]:$Clear ${Bold}$@$Clear"; }
t() { echo -e "$Dim[${BGreen}Task$Dim]:$Clear ${Bold}$@$Clear"; }
i() { echo -e "$Dim[${BBlue}Info$Dim]:$Clear ${Bold}$@$Clear"; }

Version=$1
declare Bits

case $Version in
  2.0.4 | 2.0.5 | 2.1.0-beta1 | 2.1.0-beta2 | 2.1.0-beta3 ) ;;
  * )
    err "this script only works for LuaJIT 2.0.5+"
    exit 1
    ;;
esac

case $MSYSTEM in
  MINGW32 ) Bits="32" ;;
  MINGW64 ) Bits="64" ;;
esac

FSVersion="$(echo $Version | sed 's/\.//g' | sed 's/\-//g')"
TarFilename="v$Version.tar.gz"
TarURL="https://github.com/LuaJIT/LuaJIT/archive/refs/tags/$TarFilename"
TarFolder="LuaJIT-$Version"
WorkFolder="$TarFolder-$Bits"
ZipFilename="LuaJIT_v${FSVersion}_$Bits-Bits.zip"
NSIBaseScript="LuaJITBase.nsi"
NSIScriptFilename="LuaJIT_v${FSVersion}_$Bits-Bits.nsi"
declare -A BinFiles=(
  [luajit]="luajit$FSVersion.exe"
)

i "building LuaJIT $Version ($Bits-bits)"
t "wget $TarURL"
wget $TarURL
t "tar -xf $TarFilename"
tar -xf $TarFilename
t "mv $TarFolder $WorkFolder"
mv $TarFolder $WorkFolder
t "cd $WorkFolder"
cd $WorkFolder
t "make"
make
t "cp src/*.{exe,dll} ."
cp src/*.{exe,dll} .
t "mv ${BinFiles[luajit]:0:6}.exe ${BinFiles[luajit]}"
mv "${BinFiles[luajit]:0:6}.exe" ${BinFiles[luajit]}
t "zip $ZipFilename *.exe *.dll"
zip $ZipFilename *.exe *.dll
t "mv $ZipFilename .."
mv $ZipFilename ..
t "cd .."
cd ..