#!/usr/bin/bash

Dim="\e[0;2m"
Bold="\e[0;1m"
BRed="\e[0;1;31m"
BBlue="\e[0;1;34m"
BGreen="\e[0;1;32m"
Clear="\e[0m"

err() { echo -e "$Dim[${BRed}Error$Dim]:$Clear ${Bold}$@$Clear"; }
t() { echo -e "$Dim[${BGreen}Task$Dim]:$Clear ${Bold}$@$Clear"; }
i() { echo -e "$Dim[${BBlue}Info$Dim]:$Clear ${Bold}$@$Clear"; }

Version=$1
declare Bits

case $Version in
  2.0.0 | 2.0.1 | 2.0.2 | 2.0.3 | 2.0.4 | 2.0.5 | 2.1.0-beta1 | 2.1.0-beta2 | 2.1.0-beta3 ) ;;
  * )
    err "this script only works for LuaJIT 2.0.5+"
    exit 1
    ;;
esac

case $MSYSTEM in
  MINGW32 ) Bits="32" ;;
  MINGW64 ) Bits="64" ;;
esac

FSVersion="$(echo $Version | sed 's/\.//g' | sed 's/\-//g')"
TarFilename="v$Version.tar.gz"
TarURL="https://github.com/LuaJIT/LuaJIT/archive/refs/tags/$TarFilename"
TarFolder="LuaJIT-$Version"
WorkFolder="$TarFolder-$Bits"
ZipFilename="LuaJIT_v${FSVersion}_$Bits-Bits.zip"
NSIBaseScript="LuaJITBase.nsi"
NSIScriptFilename="LuaJIT_v${FSVersion}_$Bits-Bits.nsi"
declare -A BinFiles=(
  [luajit]="luajit$FSVersion.exe"
)

i "building LuaJIT $Version ($Bits-bits)"
t "wget $TarURL"
wget $TarURL
t "tar -xf $TarFilename"
tar -xf $TarFilename
t "mv $TarFolder $WorkFolder"
mv $TarFolder $WorkFolder
t "cd $WorkFolder"
cd $WorkFolder
t "make"
make
t "cp src/*.{exe,dll} ."
cp src/*.{exe,dll} .
t "mv ${BinFiles[luajit]:0:6}.exe ${BinFiles[luajit]}"
mv "${BinFiles[luajit]:0:6}.exe" ${BinFiles[luajit]}
t "zip $ZipFilename *.exe *.dll"
zip $ZipFilename *.exe *.dll
t "mv $ZipFilename .."
mv $ZipFilename ..
t "cd .."
cd ..

LegalCopy="Since 2005, today (2022) Mike Pall."
SedScript="s/\%X\.X\.X\%/$Version/g;
s/\%AA\%/$Bits/g;
s/\%FSV\%/$FSVersion/g;
s/%LEGAL\_COPY%/$LegalCopy/g;"

case $Bits in
  32 ) SedScript+=" s/\%PROGRAM\_FILES\%/\$PROGRAMFILES/g;" ;;
  64 ) SedScript+=" s/\%PROGRAM\_FILES\%/\$PROGRAMFILES64/g;" ;;
esac

i "created sed script"
echo $SedScript > SedScript
i "created NSIS script for LuaJIT $Version"
sed -f "SedScript" $NSIBaseScript > $NSIScriptFilename
t "makensis $NSIScriptFilename"
makensis $NSIScriptFilename

RDir="Releases/$FSVersion/"
RFiles=(
  "LuaJIT_v${FSVersion}_$Bits-Bits.exe"
  "LuaJIT_v${FSVersion}_$Bits-Bits.zip"
)

t "mkdir -p $RDir"
mkdir -p $RDir
t "mv ${RFiles[@]} $RDir"
mv ${RFiles[@]} "$RDir"
t "cd $RDir"
cd "$RDir"
t "sha256sum ${RFiles[@]} >> LuaJIT_v${FSVersion}.checksums"
sha256sum ${RFiles[@]} >> "LuaJIT_v${FSVersion}.checksums"
t "cd ../../"
cd ../../

# --------
# Cleanup
i "cleaning up..."
rm -rf $WorkFolder
rm $NSIScriptFilename
rm SedScript
rm $TarFilename
i "done!"